[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "q8020-cfd-ch-lbm"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "qiskit>=2.0,<2.5",
    "qiskit_aer",
    "qiskit_ibm_runtime",
    "matplotlib",
    "numpy",
    "scipy",
    "pytest",
    "ruff",
    "q8020_cfd_metautil @ git+https://github.com/Q8020-CFD/q8020-cfd-metautil.git",
    "q8020_backend_utils[qiskit] @ git+https://github.com/Q8020-CFD/q8020-backend-utils.git",
]

# for devs of the tooling
[tool.uv.sources]
q8020_cfd_metautil = { path = "../q8020-cfd-metautil", editable = true }
q8020_backend_utils = { path = "../q8020-backend-utils", editable = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
src = ["src"]

[tool.ruff.lint.isort]
known-first-party = ["lib_classical", "lib_cole_hopf",
    "lib_cole_hopf_circuit", "lib_fd", "lib_fw", "lib_lbm",
    "lib_mps", "lib_postprocess", "lib_qalb_circuit",
    "burgers_solver"]

[tool.pylint.messages_control]
disable = [
    "C0103",  # invalid-name
    "C0305",  # trailing-newlines
    "C0303",  # trailing-whitespace
    "C0301",  # line-too-long
    "W0621",  # redefined-outer-name
    "C0413",  # wrong-import-position
    "C0116",  # missing-function-docstring
    "W0718",  # broad-exception-caught
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
