[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qcfd-mps-burgers"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "qiskit>=2.0,<3.0",
    "qiskit_aer",
    "matplotlib",
    "numpy",
    "scipy",
    "quimb",
    "numba>=0.59",
    "pytest",
    "q8020_cfd_metautil",
    "q8020_cfd_qutil",
]

[tool.uv.sources]
q8020_cfd_metautil = { path = "../q8020/q8020-cfd-metautil", editable = true }
q8020_cfd_qutil = { path = "../q8020/q8020-cfd-qutil", editable = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.pylint.messages_control]
disable = [
    "C0103",
    "C0305",
    "C0303",
    "C0301",
    "W0621",
]
